# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_ver: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_ver }}
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry lock
          poetry install --no-root --sync
      - name: Lint with flake8
        run: |
          poetry run flake8 .
      - name: Type check with mypy
        run: |
          poetry run mypy -p loopmon
      - name: Test with pytest
        run: |
          poetry run pytest tests --cov loopmon --cov-config pyproject.toml --cov-report xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: "${{ matrix.python_ver }}"
